# Generated by Django 3.1.2 on 2020-11-19 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banksys', '0003_transactionhistory_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionhistory',
            name='amount',
            field=models.FloatField(),
        ),
    ]
