# Generated by Django 3.1.2 on 2020-11-19 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banksys', '0004_auto_20201120_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='bal',
            field=models.FloatField(default=0),
        ),
    ]
